## DATABASE ##
# todo: set up environment variables for DB_URL, DB_USERNAME, DB_PASSWORD
spring:
  datasource:

    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

## JPA / HIBERNATE ##
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect

## MULTIPART (MultipartProperties) ##
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 4TB
      max-request-size: 4TB
#      location: ${UP_FILES}
#      upload-dir: ${UP_FILES}

## Server Configuration ##
server:
  port: 8080
#  servlet:
#    context-path: "/api"

  ## SWITCH/RENAME TO application.properties TO USE ##

## DATABASE ##
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  
## JPA / HIBERNATE ##
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

## MULTIPART (MultipartProperties) ##
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.file-size-threshold=2KB
#spring.servlet.multipart.max-file-size=4MB
#spring.servlet.multipart.max-request-size=8MB
#spring.servlet.multipart.location=${UP_FILES}
#spring.servlet.multipart.upload-dir=${UP_FILES}

## Server Configuration ##
#server.port=8080
#server.servlet.context-path=/api